;[
  {
    _id: '5fc3ff0c4d37f90008e5bac2',
    poster: 'bridgety',
    image: null,
    organization_id: '33810',
    activity_id: null,
    typed_content: 'Look at the great organization I found! :)',
    date_posted: '2020-11-29T20:05:32.656Z',
    attached_orgs_docs: [
      {
        _id: '5facbefe858794f85cd80e27',
        name: 'Cooperacion Comunitaria A.C.',
        mission:
          'We seek to improve the habitability conditions as well as promote resilience of indigenous, rural communities  in Mexico by facilitating a sustainable self-management of the social, economic and environmental factors for rural development. We employ holistic approaches that recover traditional knowledge and improve the relationship between society and nature.',
        logo_url: 'https://www.globalgiving.org/pfil/organ/33810/orglogo.jpg',
        url: 'http://cooperacioncomunitaria.org/',
        gg_id: '33810',
        countries: ['Mexico'],
        themes: [
          'Climate Action',
          'Disaster Response',
          'Economic Growth',
          'Education',
          'Ecosystem Restoration',
        ],
      },
    ],
    attached_activities_docs: [],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc3ff164d37f90008e5bac3',
    poster: 'bridgety',
    image: null,
    organization_id: '5054',
    activity_id: null,
    typed_content: 'Look at the great organization I found! part 2',
    date_posted: '2020-11-29T20:05:42.477Z',
    attached_orgs_docs: [
      {
        _id: '5facbd14858794f85cd7f96b',
        name: 'Foundation to Educate Girls Globally',
        mission:
          "Educate Girls' vision is to achieve behavioral, social and economic transformation towards an India where all children have equal opportunities to access quality education. We leverage existing community and government resources to ensure that all girls are in school and learning well. We aim at improving access and quality of education for 4 million children living in underserved communities in India by 2018.",
        logo_url: 'https://www.globalgiving.org/pfil/organ/5054/orglogo.jpg',
        url: 'http://www.educategirls.ngo',
        gg_id: '5054',
        countries: ['India'],
        themes: ['Child Protection', 'Education', 'Gender Equality'],
      },
    ],
    attached_activities_docs: [],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc3ff314d37f90008e5bac4',
    poster: 'bridgety',
    image: null,
    organization_id: null,
    activity_id: '5fba1b0f90f1ca3ae93a57ca',
    typed_content: 'Look at the great activity I found! hihi',
    date_posted: '2020-11-29T20:06:09.325Z',
    attached_orgs_docs: [],
    attached_activities_docs: [
      {
        _id: '5fba1b0f90f1ca3ae93a57ca',
        gg_activity_id: '2500',
        purpose:
          'The most basic need for the chimpanzees at Tchimpounga is food. Originally designed to house 30 chimpanzees, today there are more than 150 chimps at the sanctuary! It costs about $30,000 a month to feed these chimpanzees. With your help, we can reach our goal: to provide food and care for the chimps at Tchimpounga for the rest of their lives.',
        description:
          'The Tchimpounga chimpanzees sleep in spacious enclosures and have large areas of forests to roam through by day.  By exploring natural habitat together, they develop the social skills necessary for their long-term well-being.  A full-grown chimpanzee leading a healthy active life eats approximately 250 lbs. of fruits and vegetables a month, plus 30 lbs. of other staples like rice, milk and cereal.',
        contact_name: 'Brittany Cohen-Brown',
        contact_title: 'Membership & Marketing',
        contact_url: 'http://www.janegoodall.org/chimpanzees-rescue',
        contact_street_address: '1595 Spring Hill Rd',
        contact_address_additional_info: 'Suite 550',
        contact_address_city: 'Vienna',
        contact_address_country: 'United States',
        contact_address_postal_code: '22182',
        contact_address_state: 'Virginia',
        date_approved: '2009-08-28T22:06:42-04:00',
        country: 'Congo, Republic of the',
        donation_options: [
          ['25', 'buys 25 lbs. of dry goods (soya, rice, cereal, etc.)'],
          ['50', 'buys 180 lbs. of bananas'],
          ['100', 'feeds 24 chimps for 1 day'],
          ['250', 'feeds 2 chimps for 1 month'],
        ],
        goal_funding: '300000.00',
        progress_report_link:
          'https://www.globalgiving.org/projects/help-feed-over-150-orphaned-chimpanzees/updates/',
        project_link:
          'https://www.globalgiving.org/projects/help-feed-over-150-orphaned-chimpanzees/',
        region: 'Africa',
        status: 'retired',
        summary:
          "The Jane Goodall Institute's Tchimpounga Chimpanzee Rehabilitation Center (TCRC) in the Republic of Congo is home to more than 150 orphaned chimpanzees.  The chimpanzees, victims of the illegal commercial bush meat trade, often arrive at the sanctuary sick, malnourished, and close to death.  Under the skillful care of Tchimpounga's dedicated staff, these chimpanzees receive a second chance at life.",
        gg_organization_id: ['1053'],
        theme: 'Animal Welfare',
        impact:
          "JGI is committed to expanding its facilities to ensure the physical and emotional well-being of the animals under its care, as well as the safety of JGI's dedicated staff.  With the cooperation and assistance of the Congolese government and other partners, JGI is working to relocate 60 of the largest and strongest chimpanzees from the existing TCRC site to Tchindzoulou Island, one of the three islands in the Kouilou River, with the hopes of one day releasing some of them back into the wild.",
        title: 'Help Feed over 150 Orphaned Chimpanzees',
        image: 'https://www.globalgiving.org/pfil/2500/pict_grid7.jpg',
        organization_name: ['Jane Goodall Institute'],
        organization_logo_url: ['Not Specified.'],
      },
    ],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc3ff654d37f90008e5bac5',
    poster: 'bridgety',
    image:
      'https://res.cloudinary.com/charitable/image/upload/v1606680420/cfjwdv6dejfqsq3zetiw.png',
    organization_id: null,
    activity_id: null,
    typed_content: 'this is a post from my personal page pls look at this pic',
    date_posted: '2020-11-29T20:07:01.565Z',
    attached_orgs_docs: [],
    attached_activities_docs: [],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc3ffa34d37f90008e5bac6',
    poster: 'bridgety',
    image: null,
    organization_id: null,
    activity_id: null,
    typed_content: 'heres a post with no text :))) :D hdjkfhldsjlkf',
    date_posted: '2020-11-29T20:08:03.157Z',
    attached_orgs_docs: [],
    attached_activities_docs: [],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc400394d37f90008e5bac7',
    poster: 'bridgety',
    image: null,
    organization_id: null,
    activity_id: null,
    typed_content: 'hi this is the timeline',
    date_posted: '2020-11-29T20:10:33.875Z',
    attached_orgs_docs: [],
    attached_activities_docs: [],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
  {
    _id: '5fc401788fdb020005206b76',
    poster: 'bridgety',
    image: null,
    organization_id: null,
    activity_id: '5fba1b0f90f1ca3ae93a57c9',
    typed_content: 'THIS IS THE DOGS ACTIVITY!!!!!HKHHKLG!H!',
    date_posted: '2020-11-29T20:15:52.625Z',
    attached_orgs_docs: [],
    attached_activities_docs: [
      {
        _id: '5fba1b0f90f1ca3ae93a57c9',
        gg_activity_id: '6038',
        purpose:
          'The main problem is a cultural one. Many people do not see dogs as valuable. There is also a practical problem: without veterinary services, particularly sterilization, there are too many dogs competing for too few resources, making life extremely difficult for these animals. In addition, the concept of animal shelters is brand new and needs support and promotion from outside organizations.',
        description:
          '1) Advocating for  value of the human/animal relationship through community outreach, media, and local partnerships. 2) Offer a practical solution by reducing the number of dogs living on the street through spay/neuter clinics.',
        contact_name: 'Matt Webber',
        contact_title: 'Not Specified.',
        contact_url: 'http://perrosproject.org/',
        contact_street_address: '2083 NW Johnson St',
        contact_address_additional_info: '#56',
        contact_address_city: 'Portland',
        contact_address_country: 'United States',
        contact_address_postal_code: '97209',
        contact_address_state: 'OR',
        date_approved: '2010-08-25T15:00:09-04:00',
        country: 'Peru',
        donation_options: [
          ['15', 'Helps provide a perla bed for a dog at the local Huanchacito shelter'],
          ['20', 'Helps to provide needed medications'],
          ['30', 'Covers the cost to spay/neuter one dog'],
          ['60', 'Covers the cost to spay/neuter two dogs'],
          ['90', 'Covers the cost to spay/neuter three dogs'],
          [
            '500',
            'Helps pay for the airfare to fly an American vet to Huanchaco from East Coast (Miami, NYC, etc)',
          ],
          [
            '1000',
            'Helps pay for the airfare to fly an American vet to Huanchaco from West Coast (Portland, LA, etc)',
          ],
        ],
        goal_funding: '60000.00',
        progress_report_link:
          'https://www.globalgiving.org/projects/help-the-street-dogs-of-huanchaco-peru/updates/',
        project_link:
          'https://www.globalgiving.org/projects/help-the-street-dogs-of-huanchaco-peru/',
        region: 'South/Central America and the Caribbean',
        status: 'active',
        summary:
          'We send volunteers & vets to work with the municipality and local Peruvian veterinarians to conduct free spay/neuter & medical clinic work in the Huanchaco & Trujillo region of Peru. In addition, we also work to improve the local shelter.',
        gg_organization_id: ['4950'],
        theme: 'Animal Welfare',
        impact:
          'A cultural shift. The more people exposed to the benefits of sterilization and the more we can promote the value of the human/animal relationship in a town the size of Huanchaco - the better chance we have at impacting and shifting the local culture.',
        title: 'Spay & Neuter street dogs of Huanchaco, Peru',
        image: 'https://www.globalgiving.org/pfil/6038/pict_grid7.jpg',
        organization_name: ['The Perros Project'],
        organization_logo_url: ['https://www.globalgiving.org/pfil/organ/4950/orglogo.jpg'],
      },
    ],
    poster_docs: [
      {
        _id: '5fba2fe7944e9600113e6a05',
        tenant: 'charitabledev2',
        client_id: 'Oixi2FSPh9PyGesMVbnOpFcDygxMmop0',
        connection: 'MongoDB',
        email: 'boconno9@lion.lmu.edu',
        password: '$2b$10$z753BOf0z89avxk2kjGdDulho5Vqye6uXRUKJjspBVyTnZCL62gv6',
        username: 'bridgety',
        request_language: 'en-US,en;q=0.9',
        email_verified: true,
        name: 'bridget',
        profile_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678121/ghp2wco1febtl5wa9iva.png',
        banner_picture:
          'https://res.cloudinary.com/charitable/image/upload/v1606678119/r3pffxxrr4dn1pjnojnl.png',
        bio: 'it is me',
        posts: [],
        saved_orgs: [],
        saved_activities: [],
        following: [],
        nickname: 'bridgety',
      },
    ],
  },
]
